import Head from "next/head";
import Image from "next/image";
import { Nav, Navbar, Container } from "react-bootstrap";
import 'bootstrap/dist/css/bootstrap.min.css';
import styles from "@/styles/Home.module.css";
import React, { useState } from "react";

import SpeedyPaws from "@/pages/speedypaws";
import Homepage from "@/pages/homepage";
import KittyKaboom from "@/pages/kittykaboom";
import FlyKitty from "@/pages/flykitty";


// Import the functions you need from the SDKs you need
import { initializeApp } from "firebase/app";
import { getAnalytics } from "firebase/analytics";
import Cubictangle from "@/pages/cubictangle";
// https://firebase.google.com/docs/web/setup#available-libraries

// Your web app's Firebase configuration
// For Firebase JS SDK v7.20.0 and later, measurementId is optional

export default function Home() {
	const [isNetworkSwitchHighlighted, setIsNetworkSwitchHighlighted] =
		useState(false);
	const [isConnectHighlighted, setIsConnectHighlighted] = useState(false);

	const closeAll = () => {
		setIsNetworkSwitchHighlighted(false);
		setIsConnectHighlighted(false);
	};


	const showSidebar = window.innerWidth >= 768;

	const [activeLink, setActiveLink] = useState("Homepage");

	const handleLinkClick = (link:string) => {
		setActiveLink(link);
	};

	const renderPage = () => {
		switch (activeLink) {
			case "Homepage":
				return <Homepage/>;
			case "Speedy Paws":
				return <SpeedyPaws />;
			case "Kitty Kaboom":
				return <KittyKaboom />;
			case "Fly Kitty!":
				return <FlyKitty />;
			case "Cubic Tangle":
				return <Cubictangle />;
			default:
				return <Homepage/>;
		}
	};

	return (
		<>
			<Head>
				<title>WalletConnect | Next Starter Template</title>
				<meta
					name="description"
					content="Generated by create-wc-dapp"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<header>
				<div
					className={styles.backdrop}
					style={{
						opacity:
							isConnectHighlighted || isNetworkSwitchHighlighted
								? 1
								: 0,
					}}
				/>
				<div className={styles.header}>
					<div></div>
					<div className={styles.buttons}>
						<div
							onClick={closeAll}
							className={`${styles.highlight} ${
								isNetworkSwitchHighlighted
									? styles.highlightSelected
									: ``
							}`}
						>
							<w3m-network-button />
						</div>
						<div
							onClick={closeAll}
							className={`${styles.highlight} ${
								isConnectHighlighted
									? styles.highlightSelected
									: ``
							}`}
						>
							<w3m-button />
						</div>
					</div>
				</div>
			</header>
			<div className={styles.main}>
				{/* Columns for screens where columns are displayed side by side */}
				<Container className={"homepage"} fluid>
					<div className="content-container">
						<div className="sidebar">
							{/* Sidebar navigation */}

							<img className={"sitelogo"} src="/logosct.png"  alt={"site logo"}></img>
							<Nav defaultActiveKey="/home" className="flex-column">
								<Nav.Link className={"nav-link"} href="#" onClick={() => handleLinkClick("Homepage")} active={activeLink === "Homepage"}>
									<img className={"icon"} src={"/icons/home.png"}></img>
									Home

								</Nav.Link>
								<Nav.Link className={"nav-link"} href="#" onClick={() => handleLinkClick("Speedy Paws")} active={activeLink === "Speedy Paws"}>
									<img className={"icon"} src={"/icons/car.png"}></img>
									Speedy Paws
								</Nav.Link>
								<Nav.Link className={"nav-link"} href="#" onClick={() => handleLinkClick("Kitty Kaboom")} active={activeLink === "Kitty Kaboom"}>
									<img className={"icon"} src={"/icons/bomb.png"}></img>

									Kitty Kaboom
								</Nav.Link>
								<Nav.Link className={"nav-link"} href="#" onClick={() => handleLinkClick("Fly Kitty!")} active={activeLink === "Fly Kitty!"}>
									<img className={"icon"} src={"/icons/airplane.png"}></img>
									Fly Kitty!
								</Nav.Link>
								<Nav.Link className={"nav-link"} href="#" onClick={() => handleLinkClick("Cubic Tangle")} active={activeLink === "Cubic Tangle"}>
									<img className={"icon"} src={"/icons/puzzle.png"}></img>
									Cubic Tangle
								</Nav.Link>
							</Nav>
						</div>
						<div id="main-content" className={'col'}>
							{/* Render the selected page */}
							{renderPage()}
						</div>
					</div>
				</Container>
			</div>
		</>
	);
}

